import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

const getClient = (): GoogleGenAI => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found in environment variables");
  }
  return new GoogleGenAI({ apiKey });
};

export const analyzePdfContent = async (
  base64Data: string,
  prompt: string
): Promise<string> => {
  try {
    const ai = getClient();
    const model = 'gemini-2.5-flash';

    const response: GenerateContentResponse = await ai.models.generateContent({
      model,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'application/pdf',
              data: base64Data
            }
          },
          { text: prompt }
        ]
      }
    });

    return response.text || "No analysis could be generated.";
  } catch (error) {
    console.error("Gemini PDF Analysis Error:", error);
    throw new Error("Failed to analyze PDF content.");
  }
};

export const generateText = async (prompt: string, context?: string): Promise<string> => {
  try {
    const ai = getClient();
    const finalPrompt = context 
      ? `Context: ${context}\n\nTask: ${prompt}`
      : prompt;

    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: finalPrompt,
    });

    return response.text || "No response generated.";
  } catch (error) {
    console.error("Gemini Text Gen Error:", error);
    throw new Error("Failed to generate text.");
  }
};

export const generateImageDescription = async (base64Image: string, mimeType: string): Promise<string> => {
   try {
    const ai = getClient();
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: {
        parts: [
           { inlineData: { mimeType, data: base64Image } },
           { text: "Describe this image in detail." }
        ]
      }
    });
    return response.text || "Could not describe image.";
   } catch (error) {
     console.error("Image Description Error", error);
     throw error;
   }
}

export const generateIdentityPhoto = async (base64Image: string, mimeType: string): Promise<string> => {
  try {
    const ai = getClient();
    const model = 'gemini-2.5-flash-image';
    
    const prompt = `
    Edit this user's photo to be a perfect professional passport-style headshot.
    
    Strict Requirements:
    1. **Background**: CHANGE background to pure #FFFFFF (White).
    2. **Attire**: CHANGE clothing to a high-end, dark navy or black business suit with a white shirt and a random professional tie.
    3. **Composition**: Crop to standard Passport proportions (Head and shoulders only). Face should be centered.
    4. **Realism**: The image MUST look like a real DSLR photo, NOT an AI cartoon.
    
    Output ONLY the edited image.
    `;

    const response = await ai.models.generateContent({
      model,
      contents: {
        parts: [
          { inlineData: { mimeType, data: base64Image } },
          { text: prompt }
        ]
      }
    });

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return part.inlineData.data;
        }
      }
    }

    const textOutput = response.text;
    if (textOutput) {
        throw new Error(`The model returned text instead of an image.`);
    }

    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Identity Lab Error:", error);
    throw error;
  }
};

export const generateEnhancedDocument = async (base64Image: string, mimeType: string): Promise<string> => {
  try {
    const ai = getClient();
    const model = 'gemini-2.5-flash-image';
    
    const prompt = `
    You are an advanced Document Scanner AI.
    
    **INPUT**: An image containing a document (Passport, ID Card, A4 Paper) placed on a background surface.
    
    **TASK**:
    1. **ISOLATE**: Detect the main document object. 
    2. **CROP**: Crop the image TIGHTLY to the document edges. Remove ALL background (table, bedsheet, fingers, shadows outside the document).
    3. **PERSPECTIVE**: Correct the perspective. The output must be a perfect, flat, 2D top-down view of the document. Fix any skew.
    4. **ENHANCE**: 
       - Remove glare and shadows ON the document.
       - Optimize contrast for readability.
       - **CRITICAL**: Do NOT change the text content. Preserve the original pixel details of the text/logos.
    
    **OUTPUT**: Return ONLY the cropped, flattened document image. Do not add any white margins or borders in the AI output.
    `;

    const response = await ai.models.generateContent({
      model,
      contents: {
        parts: [
          { inlineData: { mimeType, data: base64Image } },
          { text: prompt }
        ]
      }
    });

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return part.inlineData.data;
        }
      }
    }
    throw new Error("No document generated.");
  } catch (error) {
    console.error("DocuScan Error:", error);
    throw error;
  }
};

export const convertPdfToWordHtml = async (base64Pdf: string): Promise<string> => {
    try {
        const ai = getClient();
        const model = 'gemini-2.5-flash';
        
        const prompt = `
        You are a high-end Document Layout Analysis engine.
        Reconstruct the attached PDF document with 100% fidelity to the original layout as HTML.
        Use HTML Tables for layout. Return a SINGLE valid HTML string.
        `;

        const response = await ai.models.generateContent({
            model,
            contents: {
                parts: [
                    { inlineData: { mimeType: 'application/pdf', data: base64Pdf } },
                    { text: prompt }
                ]
            }
        });
        
        let text = response.text || "";
        text = text.replace(/^```html/, "").replace(/```$/, "").trim();
        return text;
    } catch (error) {
        console.error("PDF to Word Error", error);
        throw new Error("Failed to convert PDF to Word.");
    }
};

export const enhanceHtmlForPdf = async (rawHtml: string): Promise<string> => {
    try {
        const ai = getClient();
        const model = 'gemini-2.5-flash';
        
        const imgMap = new Map<string, string>();
        let imgCounter = 0;
        
        const htmlWithPlaceholders = rawHtml.replace(/<img\s+[^>]*src=["']data:image\/[^;]+;base64,[^"']+["'][^>]*>/gi, (match) => {
             const placeholder = `___IMG_${imgCounter++}___`; 
             imgMap.set(placeholder, match);
             return `<div id="${placeholder}">${placeholder}</div>`; 
        });

        const prompt = `
        You are a Professional Document Formatter. 
        Style the provided HTML for a high-quality PDF export (Fonts, Margins, Table Borders).
        Preserve the image placeholders like <div id="___IMG_0___">...</div>.
        Raw HTML Input:
        ${htmlWithPlaceholders.substring(0, 45000)} 
        `;
        
        const response = await ai.models.generateContent({
            model,
            contents: prompt
        });
        
        let text = response.text || "";
        text = text.replace(/```html/g, '').replace(/```/g, '');

        imgMap.forEach((originalTag, token) => {
            const divRegex = new RegExp(`<div[^>]*id="${token}"[^>]*>.*?</div>`, 's');
            if (divRegex.test(text)) {
                 text = text.replace(divRegex, originalTag);
            } else {
                 text = text.split(token).join(originalTag);
            }
        });

        return text;
    } catch (e) {
        return rawHtml; 
    }
};

export const generateCvHtml = async (cvData: any): Promise<string> => {
  try {
    const ai = getClient();
    const model = 'gemini-3-pro-preview';

    const photoBase64 = cvData.photoBase64 || "";
    // Random Layout Logic passed from Frontend
    const layoutId = cvData.layoutId || Math.floor(Math.random() * 100) + 1;
    const jobRole = cvData.jobRole || "Professional";
    
    const aiAnalysisData = { 
        ...cvData, 
        photoBase64: photoBase64 ? "EXISTS" : null 
    };

    const prompt = `
    You are a World-Class CV Architect.
    
    **TASK**: Generate a professional HTML CV for a candidate applying for the role of: **${jobRole}**.
    **SELECTED LAYOUT ID**: Master Template #${layoutId} (Use a text-heavy, clean, professional layout).
    
    **CRITICAL REQUIREMENT - SINGLE PAGE**:
    - The output MUST fit on strictly **ONE PAGE** (A4).
    - Use CSS: \`overflow: hidden; max-height: 295mm;\` in the \`.safe-zone\` container to cut off any second page.
    - Adjust font-sizes slightly if content is too long.
    
    **CRITICAL REQUIREMENT - TYPOGRAPHY**:
    - **Font**: Use **'Times New Roman', serif** for EVERYTHING.
    - Make it attractive by using **Bold** headers, *Italics* for meta-data, and ALL-CAPS for section titles.
    - Use \`<hr>\` or border-bottoms to separate sections cleanly.

    **AUTO-CONTENT GENERATION (BE CREATIVE)**:
    1. **CAREER OBJECTIVE**: Write a strong, 3-line professional summary tailored specifically to **${jobRole}**.
    2. **SKILLS**: Generate a 'Skills' section with 8-12 hard and soft skills relevant to **${jobRole}**. Display them in a 2-column list or comma-separated block.
    3. **RESPONSIBILITIES**: For every experience entry provided, generate 3-4 professional bullet points of responsibilities typical for that role. Do NOT leave them empty.

    **MANDATORY DATA (ALL MUST BE INCLUDED)**:
    - Name (Huge Typography, Centered or Left)
    - Personal Details Block (Father Name, Religion, Nationality, DOB, CNIC, Passport No/Issue/Expiry, Place of Birth, Marital Status).
    - Address, Phone, Email.
    - Education (Degree, School, Years).
    - Experience (Designation, Company, Years) + **Generated Responsibilities**.
    
    **CSS INJECTION**:
    - Include a \`<style>\` block.
    - \`* { font-family: 'Times New Roman', serif !important; box-sizing: border-box; margin: 0; padding: 0; }\`
    - \`body { background: white; width: 210mm; height: 297mm; overflow: hidden; }\`
    - \`.safe-zone { padding: 15mm; width: 100%; height: 296mm; display: flex; flex-direction: column; overflow: hidden; }\`
    - \`.section-header { text-transform: uppercase; font-weight: bold; border-bottom: 2px solid #000; margin-top: 15px; margin-bottom: 8px; font-size: 14px; }\`
    - \`li { font-size: 12px; margin-bottom: 2px; }\`
    
    **DATA**:
    ${JSON.stringify(aiAnalysisData, null, 2)}

    **OUTPUT**:
    Return ONLY valid HTML5 code starting with <!DOCTYPE html>.
    `;

    const response = await ai.models.generateContent({
      model,
      contents: prompt,
    });

    let text = response.text || "";
    text = text.replace(/^```html/, '').replace(/```$/, '').trim();
    
    const placeholderRegex = /\[\[PHOTO_PLACEHOLDER\]\]|"%5B%5BPHOTO_PLACEHOLDER%5D%5D"|%5B%5BPHOTO_PLACEHOLDER%5D%5D/g;

    if (photoBase64) {
        const dataUri = `data:image/jpeg;base64,${photoBase64}`;
        text = text.replace(placeholderRegex, dataUri);
    } else {
        const fallback = "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI1MCIgZmlsbD0iI2UzZTNlMyIvPjwvc3ZnPg==";
        text = text.replace(placeholderRegex, fallback);
    }
    
    return text;
  } catch (error) {
    console.error("CV Generation Error:", error);
    throw new Error("Failed to generate CV template.");
  }
};

export const generateAdHtml = async (adData: any): Promise<string> => {
  try {
    const ai = getClient();
    const model = 'gemini-3-pro-preview';
    const seed = Date.now();

    const prompt = `
    You are an Expert Advertising Designer for Recruitment Agencies.
    
    **TASK**: Create a visually stunning, Vertical (9:16 Aspect Ratio) Job Advertisement HTML.
    
    **DESIGN THEME**: "ULTRA-BOLD & VISUAL".
    - **TYPOGRAPHY**: Job Titles MUST be HUGE (at least 28px), BOLD, and High Contrast.
    - **IMAGES**: Images must be LARGE and prominent (width: 100px+ or full width cards).
    - **VISIBILITY**: The text and images should be the first thing the user sees. Maximum readability.
    - Vary the layout structure based on this seed ID: ${seed}.
    - The design MUST be decent, trustworthy, and eye-catching.
    - Use gradients, shadows, and card layouts to make vacancies pop.
    
    **INPUT DATA**:
    - **Country**: ${adData.country} (FEATURE THIS PROMINENTLY, ADD FLAG ICON IF POSSIBLE)
    - **Company**: ${adData.company || "Leading Company"}
    - **Vacancies**: ${JSON.stringify(adData.jobs)}

    **MANDATORY REQUIREMENTS**:
    1. **CONTAINER**: 
       - \`width: 100%; height: 100%;\` (Targeting a 360x640px viewport).
       - Use \`display: flex; flex-direction: column;\`.
    2. **IMAGES (AI MATCHING)**: 
       - For EACH vacancy, you MUST include a relevant image.
       - **CRITICAL**: Use this exact URL format for images:
         \`https://image.pollinations.ai/prompt/{visual_description_encoded}?width=400&height=400&nologo=true&seed=${seed}&model=flux\`
       - **IMPORTANT**: 
         - Replace spaces with \`%20\` in the visual description.
         - Keep descriptions concise (max 5 words).
         - Example: \`https://image.pollinations.ai/prompt/construction%20worker%20site?width=400&height=400&nologo=true&seed=${seed}&model=flux\`
       - **FALLBACK**: Add \`onerror="this.onerror=null; this.src='https://placehold.co/400x400/1e293b/00f3ff?text=Job+Vacancy';"\` to every \`<img>\` tag to prevent broken images.
       - Style the images: LARGE, Rounded corners, shadow.
    3. **FOOTER (STRICTLY ENFORCED)**:
       - You MUST include a fixed footer at the bottom with EXACTLY this text and hierarchy:
       - **Transgulf International** (Large/Bold)
       - **Rana Trade Center Attock City**
       - **Phone No: 0572603447**
       - "Visit Office if you are interested"
    4. **LAYOUT**:
       - Header: Country/Company + Title "URGENTLY REQUIRED" (HUGE FONT).
       - Body: Grid or List of vacancies. Each item shows: LARGE Image + HUGE Job Title.
       - Footer: The mandatory contact info.

    **OUTPUT**:
    - Return ONLY valid HTML code.
    - Embed CSS in \`<style>\` tag.
    - Use Google Fonts (Montserrat, Poppins, or Bebas Neue).
    `;

    const response = await ai.models.generateContent({
      model,
      contents: prompt,
    });

    let text = response.text || "";
    text = text.replace(/^```html/, '').replace(/```$/, '').trim();
    
    return text;
  } catch (error) {
    console.error("Ad Gen Error:", error);
    throw new Error("Failed to generate Ad.");
  }
};

export const helperFileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const result = reader.result as string;
      const base64 = result.split(',')[1];
      resolve(base64);
    };
    reader.onerror = (error) => reject(error);
  });
};