import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

const getClient = (): GoogleGenAI => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found in environment variables");
  }
  return new GoogleGenAI({ apiKey });
};

export const analyzePdfContent = async (
  base64Data: string,
  prompt: string
): Promise<string> => {
  try {
    const ai = getClient();
    // Using gemini-2.5-flash as it handles documents/tokens efficiently
    const model = 'gemini-2.5-flash';

    const response: GenerateContentResponse = await ai.models.generateContent({
      model,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'application/pdf',
              data: base64Data
            }
          },
          { text: prompt }
        ]
      }
    });

    return response.text || "No analysis could be generated.";
  } catch (error) {
    console.error("Gemini PDF Analysis Error:", error);
    throw new Error("Failed to analyze PDF content.");
  }
};

export const generateText = async (prompt: string, context?: string): Promise<string> => {
  try {
    const ai = getClient();
    const finalPrompt = context 
      ? `Context: ${context}\n\nTask: ${prompt}`
      : prompt;

    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: finalPrompt,
    });

    return response.text || "No response generated.";
  } catch (error) {
    console.error("Gemini Text Gen Error:", error);
    throw new Error("Failed to generate text.");
  }
};

export const generateImageDescription = async (base64Image: string, mimeType: string): Promise<string> => {
   try {
    const ai = getClient();
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash', // Flash is multimodal
      contents: {
        parts: [
           { inlineData: { mimeType, data: base64Image } },
           { text: "Describe this image in detail." }
        ]
      }
    });
    return response.text || "Could not describe image.";
   } catch (error) {
     console.error("Image Description Error", error);
     throw error;
   }
}

export const generateIdentityPhoto = async (base64Image: string, mimeType: string): Promise<string> => {
  try {
    const ai = getClient();
    // Nano Banana model for image editing/generation
    const model = 'gemini-2.5-flash-image';
    const prompt = "Enhance Picture but look natural also when change clothes to random tie coat and shirt and also picture should be passport size even if the provided picture is full body also dont look like cartoon or generated from AI , picture should look like taken from DSLR";

    const response = await ai.models.generateContent({
      model,
      contents: {
        parts: [
          { inlineData: { mimeType, data: base64Image } },
          { text: prompt }
        ]
      }
    });

    // Extract image from parts
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return part.inlineData.data;
        }
      }
    }
    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Identity Lab Error:", error);
    throw new Error("Failed to process identity image.");
  }
};

export const convertPdfToWordHtml = async (base64Pdf: string): Promise<string> => {
    try {
        const ai = getClient();
        const model = 'gemini-2.5-flash';
        
        const prompt = `
        You are a high-end Document Layout Analysis engine specialized in converting PDFs to Microsoft Word (HTML format).

        **OBJECTIVE**: Reconstruct the attached PDF document with 100% fidelity to the original layout, typography, and content.

        **CRITICAL LAYOUT INSTRUCTIONS (WORD COMPATIBILITY)**:
        1.  **USE TABLES FOR LAYOUT**: Microsoft Word renders HTML tables perfectly. Use <table width="100%" border="0" cellpadding="0" cellspacing="0"> to create columns, sidebars, and grid layouts. Do NOT use CSS Float, Flexbox, or Grid.
        2.  **FONTS & TYPOGRAPHY**: 
            - Match the exact font family (use standard approximations like Arial, Times New Roman, Calibri, Verdana).
            - Match font size, weight (bold), and style (italic).
            - Match text alignment (left, center, right, justify) exactly.
            - Match text colors.
        3.  **COMPLEX ELEMENTS**:
            - **Tables**: Recreate data tables with exact borders, background colors, and cell merging (colspan/rowspan).
            - **Forms**: If the PDF looks like a form, use table cells with bottom borders to simulate input lines.
            - **Headers/Footers**: Place header content at the very top and footer content at the very bottom of the document body.
        4.  **IMAGES & GRAPHICS**:
            - You cannot generate binary image data. 
            - For every image, logo, or diagram, insert a placeholder: 
              <div style="width:100%; height:150px; background:#e2e8f0; border:2px dashed #94a3b8; display:flex; align-items:center; justify-content:center; color:#475569; font-family:sans-serif; margin:10px 0;">[IMAGE: Detailed description of what this image shows]</div>
        5.  **CONTENT INTEGRITY**:
            - Extract EVERY single word. Do not summarize.
            - Perform OCR on scanned text if necessary.
        
        **OUTPUT FORMAT**:
        - Return a SINGLE, valid HTML string.
        - Start with: <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
        - Include a <head> with <meta charset="utf-8">.
        - **DO NOT** use Markdown code blocks (no \`\`\`html).
        - **DO NOT** include any conversational text before or after the HTML.
        `;

        const response = await ai.models.generateContent({
            model,
            contents: {
                parts: [
                    { inlineData: { mimeType: 'application/pdf', data: base64Pdf } },
                    { text: prompt }
                ]
            }
        });
        
        let text = response.text || "";
        
        // Robust cleanup of markdown blocks if the model ignores the instruction
        text = text.trim();
        if (text.startsWith("```html")) {
            text = text.replace(/^```html/, "").replace(/```$/, "");
        } else if (text.startsWith("```")) {
            text = text.replace(/^```/, "").replace(/```$/, "");
        }
        
        return text;
    } catch (error) {
        console.error("PDF to Word Error", error);
        throw new Error("Failed to convert PDF to Word.");
    }
};

export const helperFileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const result = reader.result as string;
      // Remove data URL prefix (e.g., "data:application/pdf;base64,")
      const base64 = result.split(',')[1];
      resolve(base64);
    };
    reader.onerror = (error) => reject(error);
  });
};